name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dev
        run: echo "Building Dev"

      - name: Deploy Dev
        run: echo "Deploying to Dev"

  prod:
    needs: dev
    runs-on: ubuntu-latest
    environment:
      name: prod   # üîê Manual Approval Gate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Prod
        run: echo "Deploying to Prod"